# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Verification Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - uses: Xotabu4/selenoid-github-action@v2
    - name: Running BVT
      run: mvn clean test -Duser=$USER -Dpassword=$PASSWORD -DsuiteXmlFile='src/test/resources/SmokeTest.xml'
      env:
        USERNAME: ${{ secrets.DEF_USER }}
        PASSWORD: ${{ secrets.DEF_PASSWORD }}
    - name: Copy History
      uses: actions/checkout@v2
      if: always()
      with:
        ref: gh-pages
        path: gh-pages
    - name: Build Report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: build/allure-results
        allure_history: allure-history
        keep_reports: 20
    - name: Publish Report
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
